version: '3'
services:
  app:
    build: .
    container_name: app
    restart: always
    volumes:
      - ./app:/app
    tty: true
    depends_on:
      - db
    networks:
      - app_network
    command: bash /app/run.sh

  db:
    image: postgres:12
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ads
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  db:

networks:
  app_network: